# Generated by Django 4.0.2 on 2022-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/view/assets/img/Gallery/document/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/view/assets/img/Gallery/document/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/view/assets/img/Gallery/document/')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70)),
                ('news_title', models.CharField(blank=True, max_length=50, null=True)),
                ('news_message', models.CharField(blank=True, max_length=1200, null=True)),
                ('s_image', models.ImageField(blank=True, null=True, upload_to='static/view/assets/img/News_Picture/')),
                ('l_image1', models.ImageField(blank=True, null=True, upload_to='static/view/assets/img/News_Picture/')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone1', models.CharField(blank=True, max_length=15, null=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/view/assets/img/Gallery/picture/')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=60)),
                ('twitter', models.CharField(blank=True, max_length=60, null=True)),
                ('instagram', models.CharField(blank=True, max_length=60, null=True)),
                ('linkedin', models.TextField(blank=True, max_length=60, null=True)),
                ('dribbble', models.TextField(blank=True, max_length=60, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
