# Generated by Django 4.0.2 on 2022-02-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
