# Generated by Django 4.0.2 on 2022-02-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_alter_news_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(blank=True, max_length=65)),
                ('doc_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('number', models.CharField(blank=True, max_length=15)),
                ('bank_sl_tran', models.CharField(blank=True, max_length=60)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
