# Generated by Django 4.0.2 on 2022-02-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0003_documents_donate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donate',
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/view/assets/img/statement_pdf/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_title',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
