# Generated by Django 4.0.2 on 2022-02-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0004_delete_donate_alter_documents_doc_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=60, null=True)),
                ('ac_no', models.CharField(max_length=25, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('bkash_acc_name', models.CharField(max_length=60, null=True)),
                ('bkash_acc_number', models.CharField(max_length=25, null=True)),
                ('bkash_acc_address', models.CharField(max_length=100, null=True)),
                ('nagad_acc_name', models.CharField(max_length=60, null=True)),
                ('nagad_acc_number', models.CharField(max_length=25, null=True)),
                ('nagad_acc_address', models.CharField(max_length=100, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
