# Generated by Django 4.0.2 on 2022-03-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0005_payment_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='s_image',
            field=models.ImageField(null=True, upload_to='static/view/assets/img/News_Picture/'),
        ),
    ]
