# Generated by Django 4.0.2 on 2022-03-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0006_alter_news_s_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
