# Generated by Django 4.0.6 on 2022-07-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0007_alter_documents_doc_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/view/assets/img/statement_pdf/'),
        ),
    ]
