# Generated by Django 4.0.2 on 2022-02-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonateUs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='bank_sl_tran',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
